title: No Translation Layer LLC
url: "https://notranslationlayer.github.io"

destination: ./docs

remote_theme: jekyll/minima
minima:
  skin: dark


header_pages:
  - about.markdown
  - contact.markdown