title: No Translation Layer
url: "https://notranslationlayer.github.io"

destination: ./docs

remote_theme: jekyll/minima
minima:
  skin: classic
  social_links:
    - { platform: github,  user_url: "https://github.com/NoTranslationLayer" }
    - { platform: twitter, user_url: "https://twitter.com/NoTranslationL" }
    - { platform: reddit, user_url: "https://reddit.com/u/NoTranslationLayer" }
    - { platform: instagram, user_url: "https://instagram.com/reflect.track.anything" }
    - { platform: discord, user_url: "https://discord.gg/q4DwQu5Fwm" }


header_pages:
  - about.markdown
  - reflect.markdown
  - contact.markdown
  - blog.markdown

plugins:
  - jekyll-remote-theme
