title: No Translation Layer LLC
url: "https://notranslationlayer.github.io"

destination: ./docs

remote_theme: jekyll/minima
minima:
  skin: classic
  social_links:
    - { platform: github,  user_url: "https://github.com/NoTranslationLayer" }
    - { platform: twitter, user_url: "https://twitter.com/NoTranslationL" }
    - { platform: reddit, user_url: "https://reddit.com/u/NoTranslationLayer" }

header_pages:
  - about.markdown
  - contact.markdown

plugins:
  - jekyll-remote-theme
